import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import React, { useState } from "react";
import { useRouter } from "next/router";

const SubmitBuildPage: NextPage = () => {
  const createBuildMutation = trpc.builds.createBuild.useMutation();
  const [matchUp, setMatchUp] = useState("ZvT");
  const [style, setStyle] = useState("macro");
  const [buildOrder, setBuildOrder] = useState("");
  const [author, setAuthor] = useState("");
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");

  const router = useRouter();

  async function handleSubmitBuildOrder(e: React.FormEvent) {
    e.preventDefault();
    await createBuildMutation.mutateAsync({
      matchUp,
      build: buildOrder,
      style,
      author,
      description,
      title,
    });
    router.push("/");
  }

  return (
    <>
      <Head>
        <title>Submit a Build</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-8 bg-gray-600 text-white">
        <h1>Submit a build Order</h1>
        <form
          onSubmit={handleSubmitBuildOrder}
          className="flex w-full flex-col gap-4"
        >
          <div className="m-auto grid grid-cols-2 gap-4">
            <fieldset className="m-auto w-40">
              <label
                htmlFor="match-up-select"
                className="mb-2 block text-sm font-medium text-white"
              >
                Match Up
              </label>
              <select
                value={matchUp}
                onChange={(e) => setMatchUp(e.target.value)}
                required
                id="match-up-select"
                className="block  w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm font-semibold text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
              >
                <option value="zvt">ZvT</option>
                <option value="zvp">ZvP</option>
                <option value="zvz">ZvZ</option>

                <option value="pvt">PvT</option>
                <option value="pvp">PvP</option>
                <option value="pvz">PvZ</option>

                <option value="tvt">TvT</option>
                <option value="tvp">TvP</option>
                <option value="tvz">TvZ</option>
              </select>
            </fieldset>
            <fieldset className="m-auto w-40">
              <label
                htmlFor="style-select"
                className="mb-2 block text-sm font-medium text-white"
              >
                Style
              </label>
              <select
                value={style}
                onChange={(e) => setStyle(e.target.value)}
                required
                id="style-select"
                className="block  w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm font-semibold text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
              >
                <option value="macro">Macro</option>
                <option value="cheese">Cheese</option>
                <option value="all in">All In</option>
                <option value="timing atack">Timing Attack</option>
              </select>
            </fieldset>
          </div>

          <div className="m-auto grid grid-cols-2 gap-4">
            <fieldset className="m-auto ">
              <label
                htmlFor="author"
                className="mb-2 block text-sm font-medium text-white"
              >
                Author
              </label>

              <input
                type="text"
                required
                className="block h-10    rounded-lg border border-gray-300 bg-gray-50 p-2 p-2.5 text-sm font-semibold text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
                id="author"
                value={author}
                onChange={(e) => setAuthor(e.target.value)}
              />
            </fieldset>

            <fieldset className="m-auto ">
              <label
                htmlFor="title"
                className="mb-2 block text-sm font-medium text-white"
              >
                Title
              </label>

              <input
                type="text"
                required
                className="block h-10    rounded-lg border border-gray-300 bg-gray-50 p-2 p-2.5 text-sm font-semibold text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
                id="title"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
              />
            </fieldset>
          </div>

          <fieldset className="m-auto w-1/2">
            <label
              htmlFor="description"
              className="mb-2 block text-sm font-medium text-white"
            >
              Description
            </label>

            <textarea
              required
              className="block h-32  w-full  rounded-lg border border-gray-300 bg-gray-50 p-2 p-2.5 text-sm font-semibold text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
              id="description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
          </fieldset>

          <fieldset className="m-auto w-1/2">
            <label
              htmlFor="build-submit"
              className="mb-2 block text-sm font-medium text-white"
            >
              Build Order
            </label>

            <textarea
              required
              className="block h-[400px]  w-full  rounded-lg border border-gray-300 bg-gray-50 p-2 p-2.5 text-sm font-semibold text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
              id="build-submit"
              value={buildOrder}
              onChange={(e) => setBuildOrder(e.target.value)}
            />
          </fieldset>

          <button className=" m-auto w-60 rounded-lg border border-gray-300 bg-white px-5 py-2.5 text-sm font-medium text-gray-900 hover:bg-gray-100 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:hover:border-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-700">
            Submit
          </button>
        </form>
      </main>
    </>
  );
};

export default SubmitBuildPage;
