import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";
import { RaceCard } from "../../../../components/RaceCard";

const Races: NextPage = () => {
  const raceName = useRouter().query.raceName;
  const opponentRace = useRouter().query.opponentRace;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center gap-8 bg-gray-600 text-white ">
        <section className="flex flex-col gap-4 text-center">
          <p>{raceName}</p>
          <p>VS</p>
          <p>(Select Opponents Race)</p>
        </section>

        <ul className=" grid grid-cols-3 gap-8">
          <li>
            <RaceCard
              isOponnent
              raceImageSrc={"/zerg.jpg"}
              raceName="Zerg"
              href={`/races/${raceName}/match-up/zerg`}
            />
          </li>
          <li>
            <RaceCard
              isOponnent
              raceImageSrc={"/protoss.jpg"}
              raceName="Protoss"
              href={`/races/${raceName}/match-up/protoss`}
            />
          </li>
          <li>
            <RaceCard
              isOponnent
              raceImageSrc={"/terran.jpg"}
              raceName="Terran"
              href={`/races/${raceName}/match-up/terran`}
            />
          </li>
        </ul>
      </main>
    </>
  );
};

export default Races;
